//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Page.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.CustomerServiceSoap")]
    public interface CustomerServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 customer 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerRegister", ReplyAction="*")]
        Web_Page.CustomerService.CustomerRegisterResponse CustomerRegister(Web_Page.CustomerService.CustomerRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.CustomerRegisterResponse> CustomerRegisterAsync(Web_Page.CustomerService.CustomerRegisterRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerLogin", ReplyAction="*")]
        Web_Page.CustomerService.CustomerLoginResponse CustomerLogin(Web_Page.CustomerService.CustomerLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.CustomerLoginResponse> CustomerLoginAsync(Web_Page.CustomerService.CustomerLoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInfo", ReplyAction="*")]
        Web_Page.CustomerService.GetCustomerInfoResponse GetCustomerInfo(Web_Page.CustomerService.GetCustomerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.GetCustomerInfoResponse> GetCustomerInfoAsync(Web_Page.CustomerService.GetCustomerInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetCustomerInfoWithIDResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInfoWithID", ReplyAction="*")]
        Web_Page.CustomerService.GetCustomerInfoWithIDResponse GetCustomerInfoWithID(Web_Page.CustomerService.GetCustomerInfoWithIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInfoWithID", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.GetCustomerInfoWithIDResponse> GetCustomerInfoWithIDAsync(Web_Page.CustomerService.GetCustomerInfoWithIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomers", ReplyAction="*")]
        Web_Page.CustomerService.GetAllCustomersResponse GetAllCustomers(Web_Page.CustomerService.GetAllCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.GetAllCustomersResponse> GetAllCustomersAsync(Web_Page.CustomerService.GetAllCustomersRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerEmail", ReplyAction="*")]
        Web_Page.CustomerService.UpdateCustomerEmailResponse UpdateCustomerEmail(Web_Page.CustomerService.UpdateCustomerEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerEmailResponse> UpdateCustomerEmailAsync(Web_Page.CustomerService.UpdateCustomerEmailRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerPhone", ReplyAction="*")]
        Web_Page.CustomerService.UpdateCustomerPhoneResponse UpdateCustomerPhone(Web_Page.CustomerService.UpdateCustomerPhoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerPhone", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerPhoneResponse> UpdateCustomerPhoneAsync(Web_Page.CustomerService.UpdateCustomerPhoneRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerAddress", ReplyAction="*")]
        Web_Page.CustomerService.UpdateCustomerAddressResponse UpdateCustomerAddress(Web_Page.CustomerService.UpdateCustomerAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerAddressResponse> UpdateCustomerAddressAsync(Web_Page.CustomerService.UpdateCustomerAddressRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerPassword", ReplyAction="*")]
        Web_Page.CustomerService.UpdateCustomerPasswordResponse UpdateCustomerPassword(Web_Page.CustomerService.UpdateCustomerPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerPasswordResponse> UpdateCustomerPasswordAsync(Web_Page.CustomerService.UpdateCustomerPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerRegister", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.CustomerRegisterRequestBody Body;
        
        public CustomerRegisterRequest() {
        }
        
        public CustomerRegisterRequest(Web_Page.CustomerService.CustomerRegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerRegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.CustomerService.Customer customer;
        
        public CustomerRegisterRequestBody() {
        }
        
        public CustomerRegisterRequestBody(Web_Page.CustomerService.Customer customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerRegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.CustomerRegisterResponseBody Body;
        
        public CustomerRegisterResponse() {
        }
        
        public CustomerRegisterResponse(Web_Page.CustomerService.CustomerRegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CustomerRegisterResponseBody {
        
        public CustomerRegisterResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerLogin", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.CustomerLoginRequestBody Body;
        
        public CustomerLoginRequest() {
        }
        
        public CustomerLoginRequest(Web_Page.CustomerService.CustomerLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CustomerLoginRequestBody() {
        }
        
        public CustomerLoginRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.CustomerLoginResponseBody Body;
        
        public CustomerLoginResponse() {
        }
        
        public CustomerLoginResponse(Web_Page.CustomerService.CustomerLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CustomerLoginResult;
        
        public CustomerLoginResponseBody() {
        }
        
        public CustomerLoginResponseBody(bool CustomerLoginResult) {
            this.CustomerLoginResult = CustomerLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerInfo", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.GetCustomerInfoRequestBody Body;
        
        public GetCustomerInfoRequest() {
        }
        
        public GetCustomerInfoRequest(Web_Page.CustomerService.GetCustomerInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetCustomerInfoRequestBody() {
        }
        
        public GetCustomerInfoRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.GetCustomerInfoResponseBody Body;
        
        public GetCustomerInfoResponse() {
        }
        
        public GetCustomerInfoResponse(Web_Page.CustomerService.GetCustomerInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.CustomerService.Customer GetCustomerInfoResult;
        
        public GetCustomerInfoResponseBody() {
        }
        
        public GetCustomerInfoResponseBody(Web_Page.CustomerService.Customer GetCustomerInfoResult) {
            this.GetCustomerInfoResult = GetCustomerInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerInfoWithIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerInfoWithID", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.GetCustomerInfoWithIDRequestBody Body;
        
        public GetCustomerInfoWithIDRequest() {
        }
        
        public GetCustomerInfoWithIDRequest(Web_Page.CustomerService.GetCustomerInfoWithIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerInfoWithIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCustomerInfoWithIDRequestBody() {
        }
        
        public GetCustomerInfoWithIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerInfoWithIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerInfoWithIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.GetCustomerInfoWithIDResponseBody Body;
        
        public GetCustomerInfoWithIDResponse() {
        }
        
        public GetCustomerInfoWithIDResponse(Web_Page.CustomerService.GetCustomerInfoWithIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerInfoWithIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.CustomerService.Customer GetCustomerInfoWithIDResult;
        
        public GetCustomerInfoWithIDResponseBody() {
        }
        
        public GetCustomerInfoWithIDResponseBody(Web_Page.CustomerService.Customer GetCustomerInfoWithIDResult) {
            this.GetCustomerInfoWithIDResult = GetCustomerInfoWithIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomers", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.GetAllCustomersRequestBody Body;
        
        public GetAllCustomersRequest() {
        }
        
        public GetAllCustomersRequest(Web_Page.CustomerService.GetAllCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCustomersRequestBody {
        
        public GetAllCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.GetAllCustomersResponseBody Body;
        
        public GetAllCustomersResponse() {
        }
        
        public GetAllCustomersResponse(Web_Page.CustomerService.GetAllCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.CustomerService.Customer[] GetAllCustomersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int customersnum;
        
        public GetAllCustomersResponseBody() {
        }
        
        public GetAllCustomersResponseBody(Web_Page.CustomerService.Customer[] GetAllCustomersResult, int customersnum) {
            this.GetAllCustomersResult = GetAllCustomersResult;
            this.customersnum = customersnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerEmail", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.UpdateCustomerEmailRequestBody Body;
        
        public UpdateCustomerEmailRequest() {
        }
        
        public UpdateCustomerEmailRequest(Web_Page.CustomerService.UpdateCustomerEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public UpdateCustomerEmailRequestBody() {
        }
        
        public UpdateCustomerEmailRequestBody(string name, string email) {
            this.name = name;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.UpdateCustomerEmailResponseBody Body;
        
        public UpdateCustomerEmailResponse() {
        }
        
        public UpdateCustomerEmailResponse(Web_Page.CustomerService.UpdateCustomerEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCustomerEmailResponseBody {
        
        public UpdateCustomerEmailResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerPhone", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.UpdateCustomerPhoneRequestBody Body;
        
        public UpdateCustomerPhoneRequest() {
        }
        
        public UpdateCustomerPhoneRequest(Web_Page.CustomerService.UpdateCustomerPhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerPhoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
        
        public UpdateCustomerPhoneRequestBody() {
        }
        
        public UpdateCustomerPhoneRequestBody(string name, string phone) {
            this.name = name;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerPhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.UpdateCustomerPhoneResponseBody Body;
        
        public UpdateCustomerPhoneResponse() {
        }
        
        public UpdateCustomerPhoneResponse(Web_Page.CustomerService.UpdateCustomerPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCustomerPhoneResponseBody {
        
        public UpdateCustomerPhoneResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerAddress", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.UpdateCustomerAddressRequestBody Body;
        
        public UpdateCustomerAddressRequest() {
        }
        
        public UpdateCustomerAddressRequest(Web_Page.CustomerService.UpdateCustomerAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string address;
        
        public UpdateCustomerAddressRequestBody() {
        }
        
        public UpdateCustomerAddressRequestBody(string name, string address) {
            this.name = name;
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.UpdateCustomerAddressResponseBody Body;
        
        public UpdateCustomerAddressResponse() {
        }
        
        public UpdateCustomerAddressResponse(Web_Page.CustomerService.UpdateCustomerAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCustomerAddressResponseBody {
        
        public UpdateCustomerAddressResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerPassword", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.UpdateCustomerPasswordRequestBody Body;
        
        public UpdateCustomerPasswordRequest() {
        }
        
        public UpdateCustomerPasswordRequest(Web_Page.CustomerService.UpdateCustomerPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public UpdateCustomerPasswordRequestBody() {
        }
        
        public UpdateCustomerPasswordRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.CustomerService.UpdateCustomerPasswordResponseBody Body;
        
        public UpdateCustomerPasswordResponse() {
        }
        
        public UpdateCustomerPasswordResponse(Web_Page.CustomerService.UpdateCustomerPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCustomerPasswordResponseBody {
        
        public UpdateCustomerPasswordResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceSoapChannel : Web_Page.CustomerService.CustomerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceSoapClient : System.ServiceModel.ClientBase<Web_Page.CustomerService.CustomerServiceSoap>, Web_Page.CustomerService.CustomerServiceSoap {
        
        public CustomerServiceSoapClient() {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.CustomerRegisterResponse Web_Page.CustomerService.CustomerServiceSoap.CustomerRegister(Web_Page.CustomerService.CustomerRegisterRequest request) {
            return base.Channel.CustomerRegister(request);
        }
        
        public void CustomerRegister(Web_Page.CustomerService.Customer customer) {
            Web_Page.CustomerService.CustomerRegisterRequest inValue = new Web_Page.CustomerService.CustomerRegisterRequest();
            inValue.Body = new Web_Page.CustomerService.CustomerRegisterRequestBody();
            inValue.Body.customer = customer;
            Web_Page.CustomerService.CustomerRegisterResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).CustomerRegister(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.CustomerRegisterResponse> Web_Page.CustomerService.CustomerServiceSoap.CustomerRegisterAsync(Web_Page.CustomerService.CustomerRegisterRequest request) {
            return base.Channel.CustomerRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.CustomerRegisterResponse> CustomerRegisterAsync(Web_Page.CustomerService.Customer customer) {
            Web_Page.CustomerService.CustomerRegisterRequest inValue = new Web_Page.CustomerService.CustomerRegisterRequest();
            inValue.Body = new Web_Page.CustomerService.CustomerRegisterRequestBody();
            inValue.Body.customer = customer;
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).CustomerRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.CustomerLoginResponse Web_Page.CustomerService.CustomerServiceSoap.CustomerLogin(Web_Page.CustomerService.CustomerLoginRequest request) {
            return base.Channel.CustomerLogin(request);
        }
        
        public bool CustomerLogin(string name, string password) {
            Web_Page.CustomerService.CustomerLoginRequest inValue = new Web_Page.CustomerService.CustomerLoginRequest();
            inValue.Body = new Web_Page.CustomerService.CustomerLoginRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            Web_Page.CustomerService.CustomerLoginResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).CustomerLogin(inValue);
            return retVal.Body.CustomerLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.CustomerLoginResponse> Web_Page.CustomerService.CustomerServiceSoap.CustomerLoginAsync(Web_Page.CustomerService.CustomerLoginRequest request) {
            return base.Channel.CustomerLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.CustomerLoginResponse> CustomerLoginAsync(string name, string password) {
            Web_Page.CustomerService.CustomerLoginRequest inValue = new Web_Page.CustomerService.CustomerLoginRequest();
            inValue.Body = new Web_Page.CustomerService.CustomerLoginRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).CustomerLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.GetCustomerInfoResponse Web_Page.CustomerService.CustomerServiceSoap.GetCustomerInfo(Web_Page.CustomerService.GetCustomerInfoRequest request) {
            return base.Channel.GetCustomerInfo(request);
        }
        
        public Web_Page.CustomerService.Customer GetCustomerInfo(string name) {
            Web_Page.CustomerService.GetCustomerInfoRequest inValue = new Web_Page.CustomerService.GetCustomerInfoRequest();
            inValue.Body = new Web_Page.CustomerService.GetCustomerInfoRequestBody();
            inValue.Body.name = name;
            Web_Page.CustomerService.GetCustomerInfoResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).GetCustomerInfo(inValue);
            return retVal.Body.GetCustomerInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.GetCustomerInfoResponse> Web_Page.CustomerService.CustomerServiceSoap.GetCustomerInfoAsync(Web_Page.CustomerService.GetCustomerInfoRequest request) {
            return base.Channel.GetCustomerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.GetCustomerInfoResponse> GetCustomerInfoAsync(string name) {
            Web_Page.CustomerService.GetCustomerInfoRequest inValue = new Web_Page.CustomerService.GetCustomerInfoRequest();
            inValue.Body = new Web_Page.CustomerService.GetCustomerInfoRequestBody();
            inValue.Body.name = name;
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).GetCustomerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.GetCustomerInfoWithIDResponse Web_Page.CustomerService.CustomerServiceSoap.GetCustomerInfoWithID(Web_Page.CustomerService.GetCustomerInfoWithIDRequest request) {
            return base.Channel.GetCustomerInfoWithID(request);
        }
        
        public Web_Page.CustomerService.Customer GetCustomerInfoWithID(int id) {
            Web_Page.CustomerService.GetCustomerInfoWithIDRequest inValue = new Web_Page.CustomerService.GetCustomerInfoWithIDRequest();
            inValue.Body = new Web_Page.CustomerService.GetCustomerInfoWithIDRequestBody();
            inValue.Body.id = id;
            Web_Page.CustomerService.GetCustomerInfoWithIDResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).GetCustomerInfoWithID(inValue);
            return retVal.Body.GetCustomerInfoWithIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.GetCustomerInfoWithIDResponse> Web_Page.CustomerService.CustomerServiceSoap.GetCustomerInfoWithIDAsync(Web_Page.CustomerService.GetCustomerInfoWithIDRequest request) {
            return base.Channel.GetCustomerInfoWithIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.GetCustomerInfoWithIDResponse> GetCustomerInfoWithIDAsync(int id) {
            Web_Page.CustomerService.GetCustomerInfoWithIDRequest inValue = new Web_Page.CustomerService.GetCustomerInfoWithIDRequest();
            inValue.Body = new Web_Page.CustomerService.GetCustomerInfoWithIDRequestBody();
            inValue.Body.id = id;
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).GetCustomerInfoWithIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.GetAllCustomersResponse Web_Page.CustomerService.CustomerServiceSoap.GetAllCustomers(Web_Page.CustomerService.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomers(request);
        }
        
        public Web_Page.CustomerService.Customer[] GetAllCustomers(out int customersnum) {
            Web_Page.CustomerService.GetAllCustomersRequest inValue = new Web_Page.CustomerService.GetAllCustomersRequest();
            inValue.Body = new Web_Page.CustomerService.GetAllCustomersRequestBody();
            Web_Page.CustomerService.GetAllCustomersResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).GetAllCustomers(inValue);
            customersnum = retVal.Body.customersnum;
            return retVal.Body.GetAllCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.GetAllCustomersResponse> Web_Page.CustomerService.CustomerServiceSoap.GetAllCustomersAsync(Web_Page.CustomerService.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.GetAllCustomersResponse> GetAllCustomersAsync() {
            Web_Page.CustomerService.GetAllCustomersRequest inValue = new Web_Page.CustomerService.GetAllCustomersRequest();
            inValue.Body = new Web_Page.CustomerService.GetAllCustomersRequestBody();
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).GetAllCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.UpdateCustomerEmailResponse Web_Page.CustomerService.CustomerServiceSoap.UpdateCustomerEmail(Web_Page.CustomerService.UpdateCustomerEmailRequest request) {
            return base.Channel.UpdateCustomerEmail(request);
        }
        
        public void UpdateCustomerEmail(string name, string email) {
            Web_Page.CustomerService.UpdateCustomerEmailRequest inValue = new Web_Page.CustomerService.UpdateCustomerEmailRequest();
            inValue.Body = new Web_Page.CustomerService.UpdateCustomerEmailRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            Web_Page.CustomerService.UpdateCustomerEmailResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).UpdateCustomerEmail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerEmailResponse> Web_Page.CustomerService.CustomerServiceSoap.UpdateCustomerEmailAsync(Web_Page.CustomerService.UpdateCustomerEmailRequest request) {
            return base.Channel.UpdateCustomerEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerEmailResponse> UpdateCustomerEmailAsync(string name, string email) {
            Web_Page.CustomerService.UpdateCustomerEmailRequest inValue = new Web_Page.CustomerService.UpdateCustomerEmailRequest();
            inValue.Body = new Web_Page.CustomerService.UpdateCustomerEmailRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).UpdateCustomerEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.UpdateCustomerPhoneResponse Web_Page.CustomerService.CustomerServiceSoap.UpdateCustomerPhone(Web_Page.CustomerService.UpdateCustomerPhoneRequest request) {
            return base.Channel.UpdateCustomerPhone(request);
        }
        
        public void UpdateCustomerPhone(string name, string phone) {
            Web_Page.CustomerService.UpdateCustomerPhoneRequest inValue = new Web_Page.CustomerService.UpdateCustomerPhoneRequest();
            inValue.Body = new Web_Page.CustomerService.UpdateCustomerPhoneRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            Web_Page.CustomerService.UpdateCustomerPhoneResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).UpdateCustomerPhone(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerPhoneResponse> Web_Page.CustomerService.CustomerServiceSoap.UpdateCustomerPhoneAsync(Web_Page.CustomerService.UpdateCustomerPhoneRequest request) {
            return base.Channel.UpdateCustomerPhoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerPhoneResponse> UpdateCustomerPhoneAsync(string name, string phone) {
            Web_Page.CustomerService.UpdateCustomerPhoneRequest inValue = new Web_Page.CustomerService.UpdateCustomerPhoneRequest();
            inValue.Body = new Web_Page.CustomerService.UpdateCustomerPhoneRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).UpdateCustomerPhoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.UpdateCustomerAddressResponse Web_Page.CustomerService.CustomerServiceSoap.UpdateCustomerAddress(Web_Page.CustomerService.UpdateCustomerAddressRequest request) {
            return base.Channel.UpdateCustomerAddress(request);
        }
        
        public void UpdateCustomerAddress(string name, string address) {
            Web_Page.CustomerService.UpdateCustomerAddressRequest inValue = new Web_Page.CustomerService.UpdateCustomerAddressRequest();
            inValue.Body = new Web_Page.CustomerService.UpdateCustomerAddressRequestBody();
            inValue.Body.name = name;
            inValue.Body.address = address;
            Web_Page.CustomerService.UpdateCustomerAddressResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).UpdateCustomerAddress(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerAddressResponse> Web_Page.CustomerService.CustomerServiceSoap.UpdateCustomerAddressAsync(Web_Page.CustomerService.UpdateCustomerAddressRequest request) {
            return base.Channel.UpdateCustomerAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerAddressResponse> UpdateCustomerAddressAsync(string name, string address) {
            Web_Page.CustomerService.UpdateCustomerAddressRequest inValue = new Web_Page.CustomerService.UpdateCustomerAddressRequest();
            inValue.Body = new Web_Page.CustomerService.UpdateCustomerAddressRequestBody();
            inValue.Body.name = name;
            inValue.Body.address = address;
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).UpdateCustomerAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.CustomerService.UpdateCustomerPasswordResponse Web_Page.CustomerService.CustomerServiceSoap.UpdateCustomerPassword(Web_Page.CustomerService.UpdateCustomerPasswordRequest request) {
            return base.Channel.UpdateCustomerPassword(request);
        }
        
        public void UpdateCustomerPassword(string name, string password) {
            Web_Page.CustomerService.UpdateCustomerPasswordRequest inValue = new Web_Page.CustomerService.UpdateCustomerPasswordRequest();
            inValue.Body = new Web_Page.CustomerService.UpdateCustomerPasswordRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            Web_Page.CustomerService.UpdateCustomerPasswordResponse retVal = ((Web_Page.CustomerService.CustomerServiceSoap)(this)).UpdateCustomerPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerPasswordResponse> Web_Page.CustomerService.CustomerServiceSoap.UpdateCustomerPasswordAsync(Web_Page.CustomerService.UpdateCustomerPasswordRequest request) {
            return base.Channel.UpdateCustomerPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.CustomerService.UpdateCustomerPasswordResponse> UpdateCustomerPasswordAsync(string name, string password) {
            Web_Page.CustomerService.UpdateCustomerPasswordRequest inValue = new Web_Page.CustomerService.UpdateCustomerPasswordRequest();
            inValue.Body = new Web_Page.CustomerService.UpdateCustomerPasswordRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((Web_Page.CustomerService.CustomerServiceSoap)(this)).UpdateCustomerPasswordAsync(inValue);
        }
    }
}
