//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Page.OrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int ProductIDField;
        
        private int CustomerIDField;
        
        private int StoreIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StoreID {
            get {
                return this.StoreIDField;
            }
            set {
                if ((this.StoreIDField.Equals(value) != true)) {
                    this.StoreIDField = value;
                    this.RaisePropertyChanged("StoreID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.OrderServiceSoap")]
    public interface OrderServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderRegister", ReplyAction="*")]
        void OrderRegister(int productid, int customerid, int storeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderRegister", ReplyAction="*")]
        System.Threading.Tasks.Task OrderRegisterAsync(int productid, int customerid, int storeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderInfoForCustomer", ReplyAction="*")]
        Web_Page.OrderService.GetOrderInfoForCustomerResponse GetOrderInfoForCustomer(Web_Page.OrderService.GetOrderInfoForCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderInfoForCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.OrderService.GetOrderInfoForCustomerResponse> GetOrderInfoForCustomerAsync(Web_Page.OrderService.GetOrderInfoForCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderInfoForStore", ReplyAction="*")]
        Web_Page.OrderService.GetOrderInfoForStoreResponse GetOrderInfoForStore(Web_Page.OrderService.GetOrderInfoForStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderInfoForStore", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.OrderService.GetOrderInfoForStoreResponse> GetOrderInfoForStoreAsync(Web_Page.OrderService.GetOrderInfoForStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrders", ReplyAction="*")]
        Web_Page.OrderService.GetAllOrdersResponse GetAllOrders(Web_Page.OrderService.GetAllOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.OrderService.GetAllOrdersResponse> GetAllOrdersAsync(Web_Page.OrderService.GetAllOrdersRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 state 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrderState", ReplyAction="*")]
        Web_Page.OrderService.UpdateOrderStateResponse UpdateOrderState(Web_Page.OrderService.UpdateOrderStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrderState", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.OrderService.UpdateOrderStateResponse> UpdateOrderStateAsync(Web_Page.OrderService.UpdateOrderStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        void DeleteOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteOrderAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderInfoForCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderInfoForCustomer", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.OrderService.GetOrderInfoForCustomerRequestBody Body;
        
        public GetOrderInfoForCustomerRequest() {
        }
        
        public GetOrderInfoForCustomerRequest(Web_Page.OrderService.GetOrderInfoForCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderInfoForCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerid;
        
        public GetOrderInfoForCustomerRequestBody() {
        }
        
        public GetOrderInfoForCustomerRequestBody(int customerid) {
            this.customerid = customerid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderInfoForCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderInfoForCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.OrderService.GetOrderInfoForCustomerResponseBody Body;
        
        public GetOrderInfoForCustomerResponse() {
        }
        
        public GetOrderInfoForCustomerResponse(Web_Page.OrderService.GetOrderInfoForCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderInfoForCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.OrderService.Order[] GetOrderInfoForCustomerResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ordersnum;
        
        public GetOrderInfoForCustomerResponseBody() {
        }
        
        public GetOrderInfoForCustomerResponseBody(Web_Page.OrderService.Order[] GetOrderInfoForCustomerResult, int ordersnum) {
            this.GetOrderInfoForCustomerResult = GetOrderInfoForCustomerResult;
            this.ordersnum = ordersnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderInfoForStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderInfoForStore", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.OrderService.GetOrderInfoForStoreRequestBody Body;
        
        public GetOrderInfoForStoreRequest() {
        }
        
        public GetOrderInfoForStoreRequest(Web_Page.OrderService.GetOrderInfoForStoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderInfoForStoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int storeid;
        
        public GetOrderInfoForStoreRequestBody() {
        }
        
        public GetOrderInfoForStoreRequestBody(int storeid) {
            this.storeid = storeid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderInfoForStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderInfoForStoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.OrderService.GetOrderInfoForStoreResponseBody Body;
        
        public GetOrderInfoForStoreResponse() {
        }
        
        public GetOrderInfoForStoreResponse(Web_Page.OrderService.GetOrderInfoForStoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderInfoForStoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.OrderService.Order[] GetOrderInfoForStoreResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ordersnum;
        
        public GetOrderInfoForStoreResponseBody() {
        }
        
        public GetOrderInfoForStoreResponseBody(Web_Page.OrderService.Order[] GetOrderInfoForStoreResult, int ordersnum) {
            this.GetOrderInfoForStoreResult = GetOrderInfoForStoreResult;
            this.ordersnum = ordersnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllOrders", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.OrderService.GetAllOrdersRequestBody Body;
        
        public GetAllOrdersRequest() {
        }
        
        public GetAllOrdersRequest(Web_Page.OrderService.GetAllOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllOrdersRequestBody {
        
        public GetAllOrdersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.OrderService.GetAllOrdersResponseBody Body;
        
        public GetAllOrdersResponse() {
        }
        
        public GetAllOrdersResponse(Web_Page.OrderService.GetAllOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.OrderService.Order[] GetAllOrdersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ordersnum;
        
        public GetAllOrdersResponseBody() {
        }
        
        public GetAllOrdersResponseBody(Web_Page.OrderService.Order[] GetAllOrdersResult, int ordersnum) {
            this.GetAllOrdersResult = GetAllOrdersResult;
            this.ordersnum = ordersnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderState", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.OrderService.UpdateOrderStateRequestBody Body;
        
        public UpdateOrderStateRequest() {
        }
        
        public UpdateOrderStateRequest(Web_Page.OrderService.UpdateOrderStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrderStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string state;
        
        public UpdateOrderStateRequestBody() {
        }
        
        public UpdateOrderStateRequestBody(int id, string state) {
            this.id = id;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.OrderService.UpdateOrderStateResponseBody Body;
        
        public UpdateOrderStateResponse() {
        }
        
        public UpdateOrderStateResponse(Web_Page.OrderService.UpdateOrderStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateOrderStateResponseBody {
        
        public UpdateOrderStateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceSoapChannel : Web_Page.OrderService.OrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceSoapClient : System.ServiceModel.ClientBase<Web_Page.OrderService.OrderServiceSoap>, Web_Page.OrderService.OrderServiceSoap {
        
        public OrderServiceSoapClient() {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void OrderRegister(int productid, int customerid, int storeid) {
            base.Channel.OrderRegister(productid, customerid, storeid);
        }
        
        public System.Threading.Tasks.Task OrderRegisterAsync(int productid, int customerid, int storeid) {
            return base.Channel.OrderRegisterAsync(productid, customerid, storeid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.OrderService.GetOrderInfoForCustomerResponse Web_Page.OrderService.OrderServiceSoap.GetOrderInfoForCustomer(Web_Page.OrderService.GetOrderInfoForCustomerRequest request) {
            return base.Channel.GetOrderInfoForCustomer(request);
        }
        
        public Web_Page.OrderService.Order[] GetOrderInfoForCustomer(int customerid, out int ordersnum) {
            Web_Page.OrderService.GetOrderInfoForCustomerRequest inValue = new Web_Page.OrderService.GetOrderInfoForCustomerRequest();
            inValue.Body = new Web_Page.OrderService.GetOrderInfoForCustomerRequestBody();
            inValue.Body.customerid = customerid;
            Web_Page.OrderService.GetOrderInfoForCustomerResponse retVal = ((Web_Page.OrderService.OrderServiceSoap)(this)).GetOrderInfoForCustomer(inValue);
            ordersnum = retVal.Body.ordersnum;
            return retVal.Body.GetOrderInfoForCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.OrderService.GetOrderInfoForCustomerResponse> Web_Page.OrderService.OrderServiceSoap.GetOrderInfoForCustomerAsync(Web_Page.OrderService.GetOrderInfoForCustomerRequest request) {
            return base.Channel.GetOrderInfoForCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.OrderService.GetOrderInfoForCustomerResponse> GetOrderInfoForCustomerAsync(int customerid) {
            Web_Page.OrderService.GetOrderInfoForCustomerRequest inValue = new Web_Page.OrderService.GetOrderInfoForCustomerRequest();
            inValue.Body = new Web_Page.OrderService.GetOrderInfoForCustomerRequestBody();
            inValue.Body.customerid = customerid;
            return ((Web_Page.OrderService.OrderServiceSoap)(this)).GetOrderInfoForCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.OrderService.GetOrderInfoForStoreResponse Web_Page.OrderService.OrderServiceSoap.GetOrderInfoForStore(Web_Page.OrderService.GetOrderInfoForStoreRequest request) {
            return base.Channel.GetOrderInfoForStore(request);
        }
        
        public Web_Page.OrderService.Order[] GetOrderInfoForStore(int storeid, out int ordersnum) {
            Web_Page.OrderService.GetOrderInfoForStoreRequest inValue = new Web_Page.OrderService.GetOrderInfoForStoreRequest();
            inValue.Body = new Web_Page.OrderService.GetOrderInfoForStoreRequestBody();
            inValue.Body.storeid = storeid;
            Web_Page.OrderService.GetOrderInfoForStoreResponse retVal = ((Web_Page.OrderService.OrderServiceSoap)(this)).GetOrderInfoForStore(inValue);
            ordersnum = retVal.Body.ordersnum;
            return retVal.Body.GetOrderInfoForStoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.OrderService.GetOrderInfoForStoreResponse> Web_Page.OrderService.OrderServiceSoap.GetOrderInfoForStoreAsync(Web_Page.OrderService.GetOrderInfoForStoreRequest request) {
            return base.Channel.GetOrderInfoForStoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.OrderService.GetOrderInfoForStoreResponse> GetOrderInfoForStoreAsync(int storeid) {
            Web_Page.OrderService.GetOrderInfoForStoreRequest inValue = new Web_Page.OrderService.GetOrderInfoForStoreRequest();
            inValue.Body = new Web_Page.OrderService.GetOrderInfoForStoreRequestBody();
            inValue.Body.storeid = storeid;
            return ((Web_Page.OrderService.OrderServiceSoap)(this)).GetOrderInfoForStoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.OrderService.GetAllOrdersResponse Web_Page.OrderService.OrderServiceSoap.GetAllOrders(Web_Page.OrderService.GetAllOrdersRequest request) {
            return base.Channel.GetAllOrders(request);
        }
        
        public Web_Page.OrderService.Order[] GetAllOrders(out int ordersnum) {
            Web_Page.OrderService.GetAllOrdersRequest inValue = new Web_Page.OrderService.GetAllOrdersRequest();
            inValue.Body = new Web_Page.OrderService.GetAllOrdersRequestBody();
            Web_Page.OrderService.GetAllOrdersResponse retVal = ((Web_Page.OrderService.OrderServiceSoap)(this)).GetAllOrders(inValue);
            ordersnum = retVal.Body.ordersnum;
            return retVal.Body.GetAllOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.OrderService.GetAllOrdersResponse> Web_Page.OrderService.OrderServiceSoap.GetAllOrdersAsync(Web_Page.OrderService.GetAllOrdersRequest request) {
            return base.Channel.GetAllOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.OrderService.GetAllOrdersResponse> GetAllOrdersAsync() {
            Web_Page.OrderService.GetAllOrdersRequest inValue = new Web_Page.OrderService.GetAllOrdersRequest();
            inValue.Body = new Web_Page.OrderService.GetAllOrdersRequestBody();
            return ((Web_Page.OrderService.OrderServiceSoap)(this)).GetAllOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.OrderService.UpdateOrderStateResponse Web_Page.OrderService.OrderServiceSoap.UpdateOrderState(Web_Page.OrderService.UpdateOrderStateRequest request) {
            return base.Channel.UpdateOrderState(request);
        }
        
        public void UpdateOrderState(int id, string state) {
            Web_Page.OrderService.UpdateOrderStateRequest inValue = new Web_Page.OrderService.UpdateOrderStateRequest();
            inValue.Body = new Web_Page.OrderService.UpdateOrderStateRequestBody();
            inValue.Body.id = id;
            inValue.Body.state = state;
            Web_Page.OrderService.UpdateOrderStateResponse retVal = ((Web_Page.OrderService.OrderServiceSoap)(this)).UpdateOrderState(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.OrderService.UpdateOrderStateResponse> Web_Page.OrderService.OrderServiceSoap.UpdateOrderStateAsync(Web_Page.OrderService.UpdateOrderStateRequest request) {
            return base.Channel.UpdateOrderStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.OrderService.UpdateOrderStateResponse> UpdateOrderStateAsync(int id, string state) {
            Web_Page.OrderService.UpdateOrderStateRequest inValue = new Web_Page.OrderService.UpdateOrderStateRequest();
            inValue.Body = new Web_Page.OrderService.UpdateOrderStateRequestBody();
            inValue.Body.id = id;
            inValue.Body.state = state;
            return ((Web_Page.OrderService.OrderServiceSoap)(this)).UpdateOrderStateAsync(inValue);
        }
        
        public void DeleteOrder(int id) {
            base.Channel.DeleteOrder(id);
        }
        
        public System.Threading.Tasks.Task DeleteOrderAsync(int id) {
            return base.Channel.DeleteOrderAsync(id);
        }
    }
}
