//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Page.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int StoreIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private double PriceField;
        
        private int ViewTimesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StoreID {
            get {
                return this.StoreIDField;
            }
            set {
                if ((this.StoreIDField.Equals(value) != true)) {
                    this.StoreIDField = value;
                    this.RaisePropertyChanged("StoreID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ViewTimes {
            get {
                return this.ViewTimesField;
            }
            set {
                if ((this.ViewTimesField.Equals(value) != true)) {
                    this.ViewTimesField = value;
                    this.RaisePropertyChanged("ViewTimes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 product 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductRegister", ReplyAction="*")]
        Web_Page.ProductService.ProductRegisterResponse ProductRegister(Web_Page.ProductService.ProductRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.ProductService.ProductRegisterResponse> ProductRegisterAsync(Web_Page.ProductService.ProductRegisterRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetProductInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductInfo", ReplyAction="*")]
        Web_Page.ProductService.GetProductInfoResponse GetProductInfo(Web_Page.ProductService.GetProductInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.ProductService.GetProductInfoResponse> GetProductInfoAsync(Web_Page.ProductService.GetProductInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsInfoForStore", ReplyAction="*")]
        Web_Page.ProductService.GetProductsInfoForStoreResponse GetProductsInfoForStore(Web_Page.ProductService.GetProductsInfoForStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsInfoForStore", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.ProductService.GetProductsInfoForStoreResponse> GetProductsInfoForStoreAsync(Web_Page.ProductService.GetProductsInfoForStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        Web_Page.ProductService.GetAllProductsResponse GetAllProducts(Web_Page.ProductService.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.ProductService.GetAllProductsResponse> GetAllProductsAsync(Web_Page.ProductService.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsInfoWithName", ReplyAction="*")]
        Web_Page.ProductService.GetProductsInfoWithNameResponse GetProductsInfoWithName(Web_Page.ProductService.GetProductsInfoWithNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsInfoWithName", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.ProductService.GetProductsInfoWithNameResponse> GetProductsInfoWithNameAsync(Web_Page.ProductService.GetProductsInfoWithNameRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductName", ReplyAction="*")]
        Web_Page.ProductService.UpdateProductNameResponse UpdateProductName(Web_Page.ProductService.UpdateProductNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductName", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.ProductService.UpdateProductNameResponse> UpdateProductNameAsync(Web_Page.ProductService.UpdateProductNameRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 description 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductDescription", ReplyAction="*")]
        Web_Page.ProductService.UpdateProductDescriptionResponse UpdateProductDescription(Web_Page.ProductService.UpdateProductDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductDescription", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.ProductService.UpdateProductDescriptionResponse> UpdateProductDescriptionAsync(Web_Page.ProductService.UpdateProductDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductPrice", ReplyAction="*")]
        void UpdateProductPrice(int id, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductPrice", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateProductPriceAsync(int id, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddViewTimes", ReplyAction="*")]
        void AddViewTimes(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddViewTimes", ReplyAction="*")]
        System.Threading.Tasks.Task AddViewTimesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        void DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteProductAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductRegister", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.ProductRegisterRequestBody Body;
        
        public ProductRegisterRequest() {
        }
        
        public ProductRegisterRequest(Web_Page.ProductService.ProductRegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductRegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.ProductService.Product product;
        
        public ProductRegisterRequestBody() {
        }
        
        public ProductRegisterRequestBody(Web_Page.ProductService.Product product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductRegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.ProductRegisterResponseBody Body;
        
        public ProductRegisterResponse() {
        }
        
        public ProductRegisterResponse(Web_Page.ProductService.ProductRegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductRegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProductRegisterResult;
        
        public ProductRegisterResponseBody() {
        }
        
        public ProductRegisterResponseBody(int ProductRegisterResult) {
            this.ProductRegisterResult = ProductRegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductInfo", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.GetProductInfoRequestBody Body;
        
        public GetProductInfoRequest() {
        }
        
        public GetProductInfoRequest(Web_Page.ProductService.GetProductInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productid;
        
        public GetProductInfoRequestBody() {
        }
        
        public GetProductInfoRequestBody(int productid) {
            this.productid = productid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.GetProductInfoResponseBody Body;
        
        public GetProductInfoResponse() {
        }
        
        public GetProductInfoResponse(Web_Page.ProductService.GetProductInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.ProductService.Product GetProductInfoResult;
        
        public GetProductInfoResponseBody() {
        }
        
        public GetProductInfoResponseBody(Web_Page.ProductService.Product GetProductInfoResult) {
            this.GetProductInfoResult = GetProductInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsInfoForStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsInfoForStore", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.GetProductsInfoForStoreRequestBody Body;
        
        public GetProductsInfoForStoreRequest() {
        }
        
        public GetProductsInfoForStoreRequest(Web_Page.ProductService.GetProductsInfoForStoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsInfoForStoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int storeid;
        
        public GetProductsInfoForStoreRequestBody() {
        }
        
        public GetProductsInfoForStoreRequestBody(int storeid) {
            this.storeid = storeid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsInfoForStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsInfoForStoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.GetProductsInfoForStoreResponseBody Body;
        
        public GetProductsInfoForStoreResponse() {
        }
        
        public GetProductsInfoForStoreResponse(Web_Page.ProductService.GetProductsInfoForStoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsInfoForStoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.ProductService.Product[] GetProductsInfoForStoreResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int productsnum;
        
        public GetProductsInfoForStoreResponseBody() {
        }
        
        public GetProductsInfoForStoreResponseBody(Web_Page.ProductService.Product[] GetProductsInfoForStoreResult, int productsnum) {
            this.GetProductsInfoForStoreResult = GetProductsInfoForStoreResult;
            this.productsnum = productsnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.GetAllProductsRequestBody Body;
        
        public GetAllProductsRequest() {
        }
        
        public GetAllProductsRequest(Web_Page.ProductService.GetAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProductsRequestBody {
        
        public GetAllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.GetAllProductsResponseBody Body;
        
        public GetAllProductsResponse() {
        }
        
        public GetAllProductsResponse(Web_Page.ProductService.GetAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.ProductService.Product[] GetAllProductsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int productsnum;
        
        public GetAllProductsResponseBody() {
        }
        
        public GetAllProductsResponseBody(Web_Page.ProductService.Product[] GetAllProductsResult, int productsnum) {
            this.GetAllProductsResult = GetAllProductsResult;
            this.productsnum = productsnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsInfoWithNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsInfoWithName", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.GetProductsInfoWithNameRequestBody Body;
        
        public GetProductsInfoWithNameRequest() {
        }
        
        public GetProductsInfoWithNameRequest(Web_Page.ProductService.GetProductsInfoWithNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsInfoWithNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetProductsInfoWithNameRequestBody() {
        }
        
        public GetProductsInfoWithNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsInfoWithNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsInfoWithNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.GetProductsInfoWithNameResponseBody Body;
        
        public GetProductsInfoWithNameResponse() {
        }
        
        public GetProductsInfoWithNameResponse(Web_Page.ProductService.GetProductsInfoWithNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsInfoWithNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.ProductService.Product[] GetProductsInfoWithNameResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int productsnum;
        
        public GetProductsInfoWithNameResponseBody() {
        }
        
        public GetProductsInfoWithNameResponseBody(Web_Page.ProductService.Product[] GetProductsInfoWithNameResult, int productsnum) {
            this.GetProductsInfoWithNameResult = GetProductsInfoWithNameResult;
            this.productsnum = productsnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductName", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.UpdateProductNameRequestBody Body;
        
        public UpdateProductNameRequest() {
        }
        
        public UpdateProductNameRequest(Web_Page.ProductService.UpdateProductNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public UpdateProductNameRequestBody() {
        }
        
        public UpdateProductNameRequestBody(int id, string name) {
            this.id = id;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.UpdateProductNameResponseBody Body;
        
        public UpdateProductNameResponse() {
        }
        
        public UpdateProductNameResponse(Web_Page.ProductService.UpdateProductNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateProductNameResponseBody {
        
        public UpdateProductNameResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductDescription", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.UpdateProductDescriptionRequestBody Body;
        
        public UpdateProductDescriptionRequest() {
        }
        
        public UpdateProductDescriptionRequest(Web_Page.ProductService.UpdateProductDescriptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductDescriptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        public UpdateProductDescriptionRequestBody() {
        }
        
        public UpdateProductDescriptionRequestBody(int id, string description) {
            this.id = id;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductDescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductDescriptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.ProductService.UpdateProductDescriptionResponseBody Body;
        
        public UpdateProductDescriptionResponse() {
        }
        
        public UpdateProductDescriptionResponse(Web_Page.ProductService.UpdateProductDescriptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateProductDescriptionResponseBody {
        
        public UpdateProductDescriptionResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : Web_Page.ProductService.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<Web_Page.ProductService.ProductServiceSoap>, Web_Page.ProductService.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.ProductService.ProductRegisterResponse Web_Page.ProductService.ProductServiceSoap.ProductRegister(Web_Page.ProductService.ProductRegisterRequest request) {
            return base.Channel.ProductRegister(request);
        }
        
        public int ProductRegister(Web_Page.ProductService.Product product) {
            Web_Page.ProductService.ProductRegisterRequest inValue = new Web_Page.ProductService.ProductRegisterRequest();
            inValue.Body = new Web_Page.ProductService.ProductRegisterRequestBody();
            inValue.Body.product = product;
            Web_Page.ProductService.ProductRegisterResponse retVal = ((Web_Page.ProductService.ProductServiceSoap)(this)).ProductRegister(inValue);
            return retVal.Body.ProductRegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.ProductService.ProductRegisterResponse> Web_Page.ProductService.ProductServiceSoap.ProductRegisterAsync(Web_Page.ProductService.ProductRegisterRequest request) {
            return base.Channel.ProductRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.ProductService.ProductRegisterResponse> ProductRegisterAsync(Web_Page.ProductService.Product product) {
            Web_Page.ProductService.ProductRegisterRequest inValue = new Web_Page.ProductService.ProductRegisterRequest();
            inValue.Body = new Web_Page.ProductService.ProductRegisterRequestBody();
            inValue.Body.product = product;
            return ((Web_Page.ProductService.ProductServiceSoap)(this)).ProductRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.ProductService.GetProductInfoResponse Web_Page.ProductService.ProductServiceSoap.GetProductInfo(Web_Page.ProductService.GetProductInfoRequest request) {
            return base.Channel.GetProductInfo(request);
        }
        
        public Web_Page.ProductService.Product GetProductInfo(int productid) {
            Web_Page.ProductService.GetProductInfoRequest inValue = new Web_Page.ProductService.GetProductInfoRequest();
            inValue.Body = new Web_Page.ProductService.GetProductInfoRequestBody();
            inValue.Body.productid = productid;
            Web_Page.ProductService.GetProductInfoResponse retVal = ((Web_Page.ProductService.ProductServiceSoap)(this)).GetProductInfo(inValue);
            return retVal.Body.GetProductInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.ProductService.GetProductInfoResponse> Web_Page.ProductService.ProductServiceSoap.GetProductInfoAsync(Web_Page.ProductService.GetProductInfoRequest request) {
            return base.Channel.GetProductInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.ProductService.GetProductInfoResponse> GetProductInfoAsync(int productid) {
            Web_Page.ProductService.GetProductInfoRequest inValue = new Web_Page.ProductService.GetProductInfoRequest();
            inValue.Body = new Web_Page.ProductService.GetProductInfoRequestBody();
            inValue.Body.productid = productid;
            return ((Web_Page.ProductService.ProductServiceSoap)(this)).GetProductInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.ProductService.GetProductsInfoForStoreResponse Web_Page.ProductService.ProductServiceSoap.GetProductsInfoForStore(Web_Page.ProductService.GetProductsInfoForStoreRequest request) {
            return base.Channel.GetProductsInfoForStore(request);
        }
        
        public Web_Page.ProductService.Product[] GetProductsInfoForStore(int storeid, out int productsnum) {
            Web_Page.ProductService.GetProductsInfoForStoreRequest inValue = new Web_Page.ProductService.GetProductsInfoForStoreRequest();
            inValue.Body = new Web_Page.ProductService.GetProductsInfoForStoreRequestBody();
            inValue.Body.storeid = storeid;
            Web_Page.ProductService.GetProductsInfoForStoreResponse retVal = ((Web_Page.ProductService.ProductServiceSoap)(this)).GetProductsInfoForStore(inValue);
            productsnum = retVal.Body.productsnum;
            return retVal.Body.GetProductsInfoForStoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.ProductService.GetProductsInfoForStoreResponse> Web_Page.ProductService.ProductServiceSoap.GetProductsInfoForStoreAsync(Web_Page.ProductService.GetProductsInfoForStoreRequest request) {
            return base.Channel.GetProductsInfoForStoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.ProductService.GetProductsInfoForStoreResponse> GetProductsInfoForStoreAsync(int storeid) {
            Web_Page.ProductService.GetProductsInfoForStoreRequest inValue = new Web_Page.ProductService.GetProductsInfoForStoreRequest();
            inValue.Body = new Web_Page.ProductService.GetProductsInfoForStoreRequestBody();
            inValue.Body.storeid = storeid;
            return ((Web_Page.ProductService.ProductServiceSoap)(this)).GetProductsInfoForStoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.ProductService.GetAllProductsResponse Web_Page.ProductService.ProductServiceSoap.GetAllProducts(Web_Page.ProductService.GetAllProductsRequest request) {
            return base.Channel.GetAllProducts(request);
        }
        
        public Web_Page.ProductService.Product[] GetAllProducts(out int productsnum) {
            Web_Page.ProductService.GetAllProductsRequest inValue = new Web_Page.ProductService.GetAllProductsRequest();
            inValue.Body = new Web_Page.ProductService.GetAllProductsRequestBody();
            Web_Page.ProductService.GetAllProductsResponse retVal = ((Web_Page.ProductService.ProductServiceSoap)(this)).GetAllProducts(inValue);
            productsnum = retVal.Body.productsnum;
            return retVal.Body.GetAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.ProductService.GetAllProductsResponse> Web_Page.ProductService.ProductServiceSoap.GetAllProductsAsync(Web_Page.ProductService.GetAllProductsRequest request) {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.ProductService.GetAllProductsResponse> GetAllProductsAsync() {
            Web_Page.ProductService.GetAllProductsRequest inValue = new Web_Page.ProductService.GetAllProductsRequest();
            inValue.Body = new Web_Page.ProductService.GetAllProductsRequestBody();
            return ((Web_Page.ProductService.ProductServiceSoap)(this)).GetAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.ProductService.GetProductsInfoWithNameResponse Web_Page.ProductService.ProductServiceSoap.GetProductsInfoWithName(Web_Page.ProductService.GetProductsInfoWithNameRequest request) {
            return base.Channel.GetProductsInfoWithName(request);
        }
        
        public Web_Page.ProductService.Product[] GetProductsInfoWithName(string name, out int productsnum) {
            Web_Page.ProductService.GetProductsInfoWithNameRequest inValue = new Web_Page.ProductService.GetProductsInfoWithNameRequest();
            inValue.Body = new Web_Page.ProductService.GetProductsInfoWithNameRequestBody();
            inValue.Body.name = name;
            Web_Page.ProductService.GetProductsInfoWithNameResponse retVal = ((Web_Page.ProductService.ProductServiceSoap)(this)).GetProductsInfoWithName(inValue);
            productsnum = retVal.Body.productsnum;
            return retVal.Body.GetProductsInfoWithNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.ProductService.GetProductsInfoWithNameResponse> Web_Page.ProductService.ProductServiceSoap.GetProductsInfoWithNameAsync(Web_Page.ProductService.GetProductsInfoWithNameRequest request) {
            return base.Channel.GetProductsInfoWithNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.ProductService.GetProductsInfoWithNameResponse> GetProductsInfoWithNameAsync(string name) {
            Web_Page.ProductService.GetProductsInfoWithNameRequest inValue = new Web_Page.ProductService.GetProductsInfoWithNameRequest();
            inValue.Body = new Web_Page.ProductService.GetProductsInfoWithNameRequestBody();
            inValue.Body.name = name;
            return ((Web_Page.ProductService.ProductServiceSoap)(this)).GetProductsInfoWithNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.ProductService.UpdateProductNameResponse Web_Page.ProductService.ProductServiceSoap.UpdateProductName(Web_Page.ProductService.UpdateProductNameRequest request) {
            return base.Channel.UpdateProductName(request);
        }
        
        public void UpdateProductName(int id, string name) {
            Web_Page.ProductService.UpdateProductNameRequest inValue = new Web_Page.ProductService.UpdateProductNameRequest();
            inValue.Body = new Web_Page.ProductService.UpdateProductNameRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            Web_Page.ProductService.UpdateProductNameResponse retVal = ((Web_Page.ProductService.ProductServiceSoap)(this)).UpdateProductName(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.ProductService.UpdateProductNameResponse> Web_Page.ProductService.ProductServiceSoap.UpdateProductNameAsync(Web_Page.ProductService.UpdateProductNameRequest request) {
            return base.Channel.UpdateProductNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.ProductService.UpdateProductNameResponse> UpdateProductNameAsync(int id, string name) {
            Web_Page.ProductService.UpdateProductNameRequest inValue = new Web_Page.ProductService.UpdateProductNameRequest();
            inValue.Body = new Web_Page.ProductService.UpdateProductNameRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            return ((Web_Page.ProductService.ProductServiceSoap)(this)).UpdateProductNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.ProductService.UpdateProductDescriptionResponse Web_Page.ProductService.ProductServiceSoap.UpdateProductDescription(Web_Page.ProductService.UpdateProductDescriptionRequest request) {
            return base.Channel.UpdateProductDescription(request);
        }
        
        public void UpdateProductDescription(int id, string description) {
            Web_Page.ProductService.UpdateProductDescriptionRequest inValue = new Web_Page.ProductService.UpdateProductDescriptionRequest();
            inValue.Body = new Web_Page.ProductService.UpdateProductDescriptionRequestBody();
            inValue.Body.id = id;
            inValue.Body.description = description;
            Web_Page.ProductService.UpdateProductDescriptionResponse retVal = ((Web_Page.ProductService.ProductServiceSoap)(this)).UpdateProductDescription(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.ProductService.UpdateProductDescriptionResponse> Web_Page.ProductService.ProductServiceSoap.UpdateProductDescriptionAsync(Web_Page.ProductService.UpdateProductDescriptionRequest request) {
            return base.Channel.UpdateProductDescriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.ProductService.UpdateProductDescriptionResponse> UpdateProductDescriptionAsync(int id, string description) {
            Web_Page.ProductService.UpdateProductDescriptionRequest inValue = new Web_Page.ProductService.UpdateProductDescriptionRequest();
            inValue.Body = new Web_Page.ProductService.UpdateProductDescriptionRequestBody();
            inValue.Body.id = id;
            inValue.Body.description = description;
            return ((Web_Page.ProductService.ProductServiceSoap)(this)).UpdateProductDescriptionAsync(inValue);
        }
        
        public void UpdateProductPrice(int id, double price) {
            base.Channel.UpdateProductPrice(id, price);
        }
        
        public System.Threading.Tasks.Task UpdateProductPriceAsync(int id, double price) {
            return base.Channel.UpdateProductPriceAsync(id, price);
        }
        
        public void AddViewTimes(int id) {
            base.Channel.AddViewTimes(id);
        }
        
        public System.Threading.Tasks.Task AddViewTimesAsync(int id) {
            return base.Channel.AddViewTimesAsync(id);
        }
        
        public void DeleteProduct(int id) {
            base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
    }
}
