//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Page.StoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreService.StoreServiceSoap")]
    public interface StoreServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 store 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreRegister", ReplyAction="*")]
        Web_Page.StoreService.StoreRegisterResponse StoreRegister(Web_Page.StoreService.StoreRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.StoreService.StoreRegisterResponse> StoreRegisterAsync(Web_Page.StoreService.StoreRegisterRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreLogin", ReplyAction="*")]
        Web_Page.StoreService.StoreLoginResponse StoreLogin(Web_Page.StoreService.StoreLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.StoreService.StoreLoginResponse> StoreLoginAsync(Web_Page.StoreService.StoreLoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStoreInfo", ReplyAction="*")]
        Web_Page.StoreService.GetStoreInfoResponse GetStoreInfo(Web_Page.StoreService.GetStoreInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStoreInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.StoreService.GetStoreInfoResponse> GetStoreInfoAsync(Web_Page.StoreService.GetStoreInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetStoreInfoWithIDResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStoreInfoWithID", ReplyAction="*")]
        Web_Page.StoreService.GetStoreInfoWithIDResponse GetStoreInfoWithID(Web_Page.StoreService.GetStoreInfoWithIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStoreInfoWithID", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.StoreService.GetStoreInfoWithIDResponse> GetStoreInfoWithIDAsync(Web_Page.StoreService.GetStoreInfoWithIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStores", ReplyAction="*")]
        Web_Page.StoreService.GetAllStoresResponse GetAllStores(Web_Page.StoreService.GetAllStoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStores", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.StoreService.GetAllStoresResponse> GetAllStoresAsync(Web_Page.StoreService.GetAllStoresRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStoreEmail", ReplyAction="*")]
        Web_Page.StoreService.UpdateStoreEmailResponse UpdateStoreEmail(Web_Page.StoreService.UpdateStoreEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStoreEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStoreEmailResponse> UpdateStoreEmailAsync(Web_Page.StoreService.UpdateStoreEmailRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStorePhone", ReplyAction="*")]
        Web_Page.StoreService.UpdateStorePhoneResponse UpdateStorePhone(Web_Page.StoreService.UpdateStorePhoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStorePhone", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStorePhoneResponse> UpdateStorePhoneAsync(Web_Page.StoreService.UpdateStorePhoneRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStorePassword", ReplyAction="*")]
        Web_Page.StoreService.UpdateStorePasswordResponse UpdateStorePassword(Web_Page.StoreService.UpdateStorePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStorePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStorePasswordResponse> UpdateStorePasswordAsync(Web_Page.StoreService.UpdateStorePasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreRegister", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.StoreRegisterRequestBody Body;
        
        public StoreRegisterRequest() {
        }
        
        public StoreRegisterRequest(Web_Page.StoreService.StoreRegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StoreRegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.StoreService.Store store;
        
        public StoreRegisterRequestBody() {
        }
        
        public StoreRegisterRequestBody(Web_Page.StoreService.Store store) {
            this.store = store;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreRegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.StoreRegisterResponseBody Body;
        
        public StoreRegisterResponse() {
        }
        
        public StoreRegisterResponse(Web_Page.StoreService.StoreRegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StoreRegisterResponseBody {
        
        public StoreRegisterResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreLogin", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.StoreLoginRequestBody Body;
        
        public StoreLoginRequest() {
        }
        
        public StoreLoginRequest(Web_Page.StoreService.StoreLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StoreLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public StoreLoginRequestBody() {
        }
        
        public StoreLoginRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.StoreLoginResponseBody Body;
        
        public StoreLoginResponse() {
        }
        
        public StoreLoginResponse(Web_Page.StoreService.StoreLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StoreLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool StoreLoginResult;
        
        public StoreLoginResponseBody() {
        }
        
        public StoreLoginResponseBody(bool StoreLoginResult) {
            this.StoreLoginResult = StoreLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoreInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStoreInfo", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.GetStoreInfoRequestBody Body;
        
        public GetStoreInfoRequest() {
        }
        
        public GetStoreInfoRequest(Web_Page.StoreService.GetStoreInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStoreInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetStoreInfoRequestBody() {
        }
        
        public GetStoreInfoRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoreInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStoreInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.GetStoreInfoResponseBody Body;
        
        public GetStoreInfoResponse() {
        }
        
        public GetStoreInfoResponse(Web_Page.StoreService.GetStoreInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStoreInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.StoreService.Store GetStoreInfoResult;
        
        public GetStoreInfoResponseBody() {
        }
        
        public GetStoreInfoResponseBody(Web_Page.StoreService.Store GetStoreInfoResult) {
            this.GetStoreInfoResult = GetStoreInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoreInfoWithIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStoreInfoWithID", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.GetStoreInfoWithIDRequestBody Body;
        
        public GetStoreInfoWithIDRequest() {
        }
        
        public GetStoreInfoWithIDRequest(Web_Page.StoreService.GetStoreInfoWithIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStoreInfoWithIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetStoreInfoWithIDRequestBody() {
        }
        
        public GetStoreInfoWithIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoreInfoWithIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStoreInfoWithIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.GetStoreInfoWithIDResponseBody Body;
        
        public GetStoreInfoWithIDResponse() {
        }
        
        public GetStoreInfoWithIDResponse(Web_Page.StoreService.GetStoreInfoWithIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStoreInfoWithIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.StoreService.Store GetStoreInfoWithIDResult;
        
        public GetStoreInfoWithIDResponseBody() {
        }
        
        public GetStoreInfoWithIDResponseBody(Web_Page.StoreService.Store GetStoreInfoWithIDResult) {
            this.GetStoreInfoWithIDResult = GetStoreInfoWithIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStores", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.GetAllStoresRequestBody Body;
        
        public GetAllStoresRequest() {
        }
        
        public GetAllStoresRequest(Web_Page.StoreService.GetAllStoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllStoresRequestBody {
        
        public GetAllStoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.GetAllStoresResponseBody Body;
        
        public GetAllStoresResponse() {
        }
        
        public GetAllStoresResponse(Web_Page.StoreService.GetAllStoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web_Page.StoreService.Store[] GetAllStoresResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int storesnum;
        
        public GetAllStoresResponseBody() {
        }
        
        public GetAllStoresResponseBody(Web_Page.StoreService.Store[] GetAllStoresResult, int storesnum) {
            this.GetAllStoresResult = GetAllStoresResult;
            this.storesnum = storesnum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStoreEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStoreEmail", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.UpdateStoreEmailRequestBody Body;
        
        public UpdateStoreEmailRequest() {
        }
        
        public UpdateStoreEmailRequest(Web_Page.StoreService.UpdateStoreEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStoreEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public UpdateStoreEmailRequestBody() {
        }
        
        public UpdateStoreEmailRequestBody(string name, string email) {
            this.name = name;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStoreEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStoreEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.UpdateStoreEmailResponseBody Body;
        
        public UpdateStoreEmailResponse() {
        }
        
        public UpdateStoreEmailResponse(Web_Page.StoreService.UpdateStoreEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateStoreEmailResponseBody {
        
        public UpdateStoreEmailResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStorePhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStorePhone", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.UpdateStorePhoneRequestBody Body;
        
        public UpdateStorePhoneRequest() {
        }
        
        public UpdateStorePhoneRequest(Web_Page.StoreService.UpdateStorePhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStorePhoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phone;
        
        public UpdateStorePhoneRequestBody() {
        }
        
        public UpdateStorePhoneRequestBody(string name, string phone) {
            this.name = name;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStorePhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStorePhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.UpdateStorePhoneResponseBody Body;
        
        public UpdateStorePhoneResponse() {
        }
        
        public UpdateStorePhoneResponse(Web_Page.StoreService.UpdateStorePhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateStorePhoneResponseBody {
        
        public UpdateStorePhoneResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStorePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStorePassword", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.UpdateStorePasswordRequestBody Body;
        
        public UpdateStorePasswordRequest() {
        }
        
        public UpdateStorePasswordRequest(Web_Page.StoreService.UpdateStorePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStorePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public UpdateStorePasswordRequestBody() {
        }
        
        public UpdateStorePasswordRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStorePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStorePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web_Page.StoreService.UpdateStorePasswordResponseBody Body;
        
        public UpdateStorePasswordResponse() {
        }
        
        public UpdateStorePasswordResponse(Web_Page.StoreService.UpdateStorePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateStorePasswordResponseBody {
        
        public UpdateStorePasswordResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StoreServiceSoapChannel : Web_Page.StoreService.StoreServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreServiceSoapClient : System.ServiceModel.ClientBase<Web_Page.StoreService.StoreServiceSoap>, Web_Page.StoreService.StoreServiceSoap {
        
        public StoreServiceSoapClient() {
        }
        
        public StoreServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.StoreService.StoreRegisterResponse Web_Page.StoreService.StoreServiceSoap.StoreRegister(Web_Page.StoreService.StoreRegisterRequest request) {
            return base.Channel.StoreRegister(request);
        }
        
        public void StoreRegister(Web_Page.StoreService.Store store) {
            Web_Page.StoreService.StoreRegisterRequest inValue = new Web_Page.StoreService.StoreRegisterRequest();
            inValue.Body = new Web_Page.StoreService.StoreRegisterRequestBody();
            inValue.Body.store = store;
            Web_Page.StoreService.StoreRegisterResponse retVal = ((Web_Page.StoreService.StoreServiceSoap)(this)).StoreRegister(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.StoreService.StoreRegisterResponse> Web_Page.StoreService.StoreServiceSoap.StoreRegisterAsync(Web_Page.StoreService.StoreRegisterRequest request) {
            return base.Channel.StoreRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.StoreService.StoreRegisterResponse> StoreRegisterAsync(Web_Page.StoreService.Store store) {
            Web_Page.StoreService.StoreRegisterRequest inValue = new Web_Page.StoreService.StoreRegisterRequest();
            inValue.Body = new Web_Page.StoreService.StoreRegisterRequestBody();
            inValue.Body.store = store;
            return ((Web_Page.StoreService.StoreServiceSoap)(this)).StoreRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.StoreService.StoreLoginResponse Web_Page.StoreService.StoreServiceSoap.StoreLogin(Web_Page.StoreService.StoreLoginRequest request) {
            return base.Channel.StoreLogin(request);
        }
        
        public bool StoreLogin(string name, string password) {
            Web_Page.StoreService.StoreLoginRequest inValue = new Web_Page.StoreService.StoreLoginRequest();
            inValue.Body = new Web_Page.StoreService.StoreLoginRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            Web_Page.StoreService.StoreLoginResponse retVal = ((Web_Page.StoreService.StoreServiceSoap)(this)).StoreLogin(inValue);
            return retVal.Body.StoreLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.StoreService.StoreLoginResponse> Web_Page.StoreService.StoreServiceSoap.StoreLoginAsync(Web_Page.StoreService.StoreLoginRequest request) {
            return base.Channel.StoreLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.StoreService.StoreLoginResponse> StoreLoginAsync(string name, string password) {
            Web_Page.StoreService.StoreLoginRequest inValue = new Web_Page.StoreService.StoreLoginRequest();
            inValue.Body = new Web_Page.StoreService.StoreLoginRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((Web_Page.StoreService.StoreServiceSoap)(this)).StoreLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.StoreService.GetStoreInfoResponse Web_Page.StoreService.StoreServiceSoap.GetStoreInfo(Web_Page.StoreService.GetStoreInfoRequest request) {
            return base.Channel.GetStoreInfo(request);
        }
        
        public Web_Page.StoreService.Store GetStoreInfo(string name) {
            Web_Page.StoreService.GetStoreInfoRequest inValue = new Web_Page.StoreService.GetStoreInfoRequest();
            inValue.Body = new Web_Page.StoreService.GetStoreInfoRequestBody();
            inValue.Body.name = name;
            Web_Page.StoreService.GetStoreInfoResponse retVal = ((Web_Page.StoreService.StoreServiceSoap)(this)).GetStoreInfo(inValue);
            return retVal.Body.GetStoreInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.StoreService.GetStoreInfoResponse> Web_Page.StoreService.StoreServiceSoap.GetStoreInfoAsync(Web_Page.StoreService.GetStoreInfoRequest request) {
            return base.Channel.GetStoreInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.StoreService.GetStoreInfoResponse> GetStoreInfoAsync(string name) {
            Web_Page.StoreService.GetStoreInfoRequest inValue = new Web_Page.StoreService.GetStoreInfoRequest();
            inValue.Body = new Web_Page.StoreService.GetStoreInfoRequestBody();
            inValue.Body.name = name;
            return ((Web_Page.StoreService.StoreServiceSoap)(this)).GetStoreInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.StoreService.GetStoreInfoWithIDResponse Web_Page.StoreService.StoreServiceSoap.GetStoreInfoWithID(Web_Page.StoreService.GetStoreInfoWithIDRequest request) {
            return base.Channel.GetStoreInfoWithID(request);
        }
        
        public Web_Page.StoreService.Store GetStoreInfoWithID(int id) {
            Web_Page.StoreService.GetStoreInfoWithIDRequest inValue = new Web_Page.StoreService.GetStoreInfoWithIDRequest();
            inValue.Body = new Web_Page.StoreService.GetStoreInfoWithIDRequestBody();
            inValue.Body.id = id;
            Web_Page.StoreService.GetStoreInfoWithIDResponse retVal = ((Web_Page.StoreService.StoreServiceSoap)(this)).GetStoreInfoWithID(inValue);
            return retVal.Body.GetStoreInfoWithIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.StoreService.GetStoreInfoWithIDResponse> Web_Page.StoreService.StoreServiceSoap.GetStoreInfoWithIDAsync(Web_Page.StoreService.GetStoreInfoWithIDRequest request) {
            return base.Channel.GetStoreInfoWithIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.StoreService.GetStoreInfoWithIDResponse> GetStoreInfoWithIDAsync(int id) {
            Web_Page.StoreService.GetStoreInfoWithIDRequest inValue = new Web_Page.StoreService.GetStoreInfoWithIDRequest();
            inValue.Body = new Web_Page.StoreService.GetStoreInfoWithIDRequestBody();
            inValue.Body.id = id;
            return ((Web_Page.StoreService.StoreServiceSoap)(this)).GetStoreInfoWithIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.StoreService.GetAllStoresResponse Web_Page.StoreService.StoreServiceSoap.GetAllStores(Web_Page.StoreService.GetAllStoresRequest request) {
            return base.Channel.GetAllStores(request);
        }
        
        public Web_Page.StoreService.Store[] GetAllStores(out int storesnum) {
            Web_Page.StoreService.GetAllStoresRequest inValue = new Web_Page.StoreService.GetAllStoresRequest();
            inValue.Body = new Web_Page.StoreService.GetAllStoresRequestBody();
            Web_Page.StoreService.GetAllStoresResponse retVal = ((Web_Page.StoreService.StoreServiceSoap)(this)).GetAllStores(inValue);
            storesnum = retVal.Body.storesnum;
            return retVal.Body.GetAllStoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.StoreService.GetAllStoresResponse> Web_Page.StoreService.StoreServiceSoap.GetAllStoresAsync(Web_Page.StoreService.GetAllStoresRequest request) {
            return base.Channel.GetAllStoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.StoreService.GetAllStoresResponse> GetAllStoresAsync() {
            Web_Page.StoreService.GetAllStoresRequest inValue = new Web_Page.StoreService.GetAllStoresRequest();
            inValue.Body = new Web_Page.StoreService.GetAllStoresRequestBody();
            return ((Web_Page.StoreService.StoreServiceSoap)(this)).GetAllStoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.StoreService.UpdateStoreEmailResponse Web_Page.StoreService.StoreServiceSoap.UpdateStoreEmail(Web_Page.StoreService.UpdateStoreEmailRequest request) {
            return base.Channel.UpdateStoreEmail(request);
        }
        
        public void UpdateStoreEmail(string name, string email) {
            Web_Page.StoreService.UpdateStoreEmailRequest inValue = new Web_Page.StoreService.UpdateStoreEmailRequest();
            inValue.Body = new Web_Page.StoreService.UpdateStoreEmailRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            Web_Page.StoreService.UpdateStoreEmailResponse retVal = ((Web_Page.StoreService.StoreServiceSoap)(this)).UpdateStoreEmail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStoreEmailResponse> Web_Page.StoreService.StoreServiceSoap.UpdateStoreEmailAsync(Web_Page.StoreService.UpdateStoreEmailRequest request) {
            return base.Channel.UpdateStoreEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStoreEmailResponse> UpdateStoreEmailAsync(string name, string email) {
            Web_Page.StoreService.UpdateStoreEmailRequest inValue = new Web_Page.StoreService.UpdateStoreEmailRequest();
            inValue.Body = new Web_Page.StoreService.UpdateStoreEmailRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            return ((Web_Page.StoreService.StoreServiceSoap)(this)).UpdateStoreEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.StoreService.UpdateStorePhoneResponse Web_Page.StoreService.StoreServiceSoap.UpdateStorePhone(Web_Page.StoreService.UpdateStorePhoneRequest request) {
            return base.Channel.UpdateStorePhone(request);
        }
        
        public void UpdateStorePhone(string name, string phone) {
            Web_Page.StoreService.UpdateStorePhoneRequest inValue = new Web_Page.StoreService.UpdateStorePhoneRequest();
            inValue.Body = new Web_Page.StoreService.UpdateStorePhoneRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            Web_Page.StoreService.UpdateStorePhoneResponse retVal = ((Web_Page.StoreService.StoreServiceSoap)(this)).UpdateStorePhone(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStorePhoneResponse> Web_Page.StoreService.StoreServiceSoap.UpdateStorePhoneAsync(Web_Page.StoreService.UpdateStorePhoneRequest request) {
            return base.Channel.UpdateStorePhoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStorePhoneResponse> UpdateStorePhoneAsync(string name, string phone) {
            Web_Page.StoreService.UpdateStorePhoneRequest inValue = new Web_Page.StoreService.UpdateStorePhoneRequest();
            inValue.Body = new Web_Page.StoreService.UpdateStorePhoneRequestBody();
            inValue.Body.name = name;
            inValue.Body.phone = phone;
            return ((Web_Page.StoreService.StoreServiceSoap)(this)).UpdateStorePhoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Page.StoreService.UpdateStorePasswordResponse Web_Page.StoreService.StoreServiceSoap.UpdateStorePassword(Web_Page.StoreService.UpdateStorePasswordRequest request) {
            return base.Channel.UpdateStorePassword(request);
        }
        
        public void UpdateStorePassword(string name, string password) {
            Web_Page.StoreService.UpdateStorePasswordRequest inValue = new Web_Page.StoreService.UpdateStorePasswordRequest();
            inValue.Body = new Web_Page.StoreService.UpdateStorePasswordRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            Web_Page.StoreService.UpdateStorePasswordResponse retVal = ((Web_Page.StoreService.StoreServiceSoap)(this)).UpdateStorePassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStorePasswordResponse> Web_Page.StoreService.StoreServiceSoap.UpdateStorePasswordAsync(Web_Page.StoreService.UpdateStorePasswordRequest request) {
            return base.Channel.UpdateStorePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web_Page.StoreService.UpdateStorePasswordResponse> UpdateStorePasswordAsync(string name, string password) {
            Web_Page.StoreService.UpdateStorePasswordRequest inValue = new Web_Page.StoreService.UpdateStorePasswordRequest();
            inValue.Body = new Web_Page.StoreService.UpdateStorePasswordRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((Web_Page.StoreService.StoreServiceSoap)(this)).UpdateStorePasswordAsync(inValue);
        }
    }
}
